trecnoc/concourse-pipelines

scripts/fetch-bosh-releases-from-manifest.sh, scripts/process-bosh-deployment-repo.sh, scripts/process-cf-deployment-release.sh, scripts/process-tools.sh
Prevent failing builds right away on curl connection issues.
=> Adding retries to curl

scripts/process-cf-cli.sh
- In addition to Linux RPM and Windows installer, also grab the Windows standalone ZIP file.
- Update echo statements to reflect the truth!
=> Update process-cf-cli.sh script.

pipelines/director.yml, scripts/process-bosh-deployment-repo.sh
=> Fetch Bosh-Dns release specified from runtime-config

pipelines/buildpacks.yml
=> DotNet now only support CFLinuxFS3

pipelines/cf.yml
=> Update CF pipeline to fetch version 5.5.0

pipelines/buildpacks.yml
=> Update Ruby buildpack job to only process CFLinuxFS3

pipelines/doomsday.yml
=> Fix glob for doomsday CLI

scripts/process-buildpack.sh
Package list is always included in the release notes
=> Remove buildpack release packages.md file

pipelines/buildpacks.yml, pipelines/cf.yml, pipelines/common.yml, pipelines/concourse.yml, pipelines/director.yml, pipelines/doomsday.yml, pipelines/logsearch.yml, pipelines/mattermost.yml, pipelines/minio.yml, pipelines/mysql.yml, pipelines/rabbitmq.yml, pipelines/redis.yml, pipelines/test-deployment.yml
The webhook has been configured with the Concourse icon.
=> Remove the icon override on successes

high-pipelines/buildpacks/reconfigure-all, high-pipelines/buildpacks/reconfigure-pipeline
Also made teh reconfigure-pipeline non-interactive
=> Add script to reconfigure all buildpacks pipeline

.gitignore, credentials.yml.template, docs/configuration.md, generate_credentials.sh
Helper script to generate all the required credentials in the correct 
format.
=> Credential file generator

pipelines/common.yml, scripts/copy-bosh-io-stemcell.sh
=> Clean-up common pipeline

pipelines/mattermost.yml
=> Cleanup Mattermost pipeline

pipelines/rabbitmq.yml
=> Cleanup RabbitMQ Pipeline

pipelines/redis.yml
=> Cleanup of the Redis pipeline

pipelines/test-deployment.yml
=> Cleanup Test-Deployment Pipeline

pipelines/doomsday.yml
=> Cleanup Doomsday Pipeline

pipelines/logsearch.yml
=> Cleanup Logsearch pipeline

README.md, docs/configuration.md, docs/install-concourse.md, docs/install-docker.md, docs/server-preparation.md, pipelines/common.yml, pipelines/director.yml
- Documented the differences between the BW, AVA and local setups.
- Also update common.yml and director.yml pipelines groups name to not
use the deprecated format (can't use capital letters)
=> Updating documentation

pipelines/prometheus.yml, set_pipelines.sh
=> Add Prometheus pipeline

docs/install-concourse.md
=> Add instruction for enable global resources

pipelines/buildpacks.yml, pipelines/cf.yml, pipelines/common.yml, pipelines/concourse.yml, pipelines/director.yml, pipelines/doomsday.yml, pipelines/logsearch.yml, pipelines/mattermost.yml, pipelines/minio.yml, pipelines/mysql.yml, pipelines/postgres-cluster.yml, pipelines/prometheus.yml, pipelines/rabbitmq.yml, pipelines/redis.yml, pipelines/test-deployment.yml, samples/nexus.yml
=> Replace docker-image with registry-image resource

pipelines/common.yml
=> Mirror Bionic Stemcells

pipelines/rabbitmq.yml
=> Build the RabbitMQ releases until they are published on bosh.io

pipelines/cf.yml, pipelines/prometheus.yml
Also noticed that cf-mgmt had changed github org, updated the pipeline
=> Mirror cron-boshrelease
